apiVersion: v2
name: k8s-ssh-bastion
description: A lightweight, secure SSH bastion for Kubernetes
type: application
version: 0.6.0
appVersion: "24.04"
keywords:
  - ssh
  - bastion
  - security
  - access
  - jump-host
home: https://github.com/rvvg/k8s-ssh-bastion
sources:
  - https://github.com/rvvg/k8s-ssh-bastion
maintainers:
  - name: rvvg
    url: https://github.com/rvvg
