---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/users: {{ toJson .Values.users | sha256sum }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: bastion
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag $ }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -ec
            - |
              apt-get update && apt-get install -y openssh-server zsh
              cd /etc/ssh
              
              # Ensure public keys exist (for mounted keys)
              for ssh_key in /etc/ssh/ssh_host_*_key; do
                if [ ! -f ${ssh_key}.pub ]; then
                  ssh-keygen -y -f ${ssh_key} > ${ssh_key}.pub
                fi
              done

              # Create users based on mounted authorized_keys
              USER_UID=1001
              for i in /etc/ssh/authorized_keys/*; do
                if [ -f "$i" ]; then
                  username=$(basename "$i")
                  useradd -rm -d /home/$username -s /bin/bash -g root -u $((USER_UID++)) $username
                  chown -R $username:nogroup /home/$username
                fi
              done

              mkdir -p /run/sshd

              {{- with .Values.initscripts }}
              {{- range $key, $value := . }}
              /usr/share/initscripts/{{ $key }}
              {{- end }}
              {{- end }}

              /usr/sbin/sshd -D -e -E /proc/1/fd/1
          lifecycle: {{ .Values.lifecycle | toJson }}
          resources: {{ .Values.resources | toJson }}
          ports:
            - name: ssh
              containerPort: 1022
              protocol: TCP
          volumeMounts:
          - name: users
            mountPath: /etc/ssh/authorized_keys
          - name: usr-share-initscripts
            mountPath: /usr/share/initscripts
          {{- range $key, $value := .Values.ssh }}
          - name: sshd-configs
            mountPath: /etc/ssh/{{ $key }}
            subPath: {{ $key }}
          {{- end }}
          - name: host-keys
            mountPath: /etc/ssh/ssh_host_rsa_key
            subPath: ssh_host_rsa_key
            readOnly: true
          - name: host-keys
            mountPath: /etc/ssh/ssh_host_ecdsa_key
            subPath: ssh_host_ecdsa_key
            readOnly: true
          - name: host-keys
            mountPath: /etc/ssh/ssh_host_ed25519_key
            subPath: ssh_host_ed25519_key
            readOnly: true
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.dnsConfig }}
      dnsConfig: {{ . | toJson }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      affinity: {{ .Values.affinity | toJson }}
      imagePullSecrets: {{ .Values.image.imagePullSecrets | toJson }}
{{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
{{- end }}
      volumes:
      - name: users
        secret:
          secretName: {{ .Release.Name }}-users
          defaultMode: 0600
      - name: sshd-configs
        configMap:
          name: {{ .Release.Name }}-etc-ssh
          defaultMode: 0600
      - name: usr-share-initscripts
        configMap:
          name: {{ .Release.Name }}-usr-share-initscripts
          defaultMode: 0755
      - name: host-keys
        secret:
          secretName: {{ .Release.Name }}-host-keys
          defaultMode: 0600

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-etc-ssh
data:
{{ tpl (toYaml .Values.ssh) $ | indent 2 }}

---
# Additional startup commands
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-usr-share-initscripts
data:
{{ tpl (toYaml .Values.initscripts) $ | indent 2 }}
