apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- range $user, $key := .Values.users }}
  {{ $user }}: {{ $key | b64enc }}
  {{- end }}
